#############################################################################
# Makefile for building: Bora-qt
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  Bora.pro
# Template: app
# Command: c:/Qt/5.10.1_MinGW_static/bin/qmake.exe -o Makefile Bora.pro CONFIG+=release
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = c:/Qt/5.10.1_MinGW_static/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = c:/Qt/5.10.1_MinGW_static/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = c:/Qt/5.10.1_MinGW_static/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Bora.pro ../../Qt/5.10.1_MinGW_static/mkspecs/win32-g++/qmake.conf ../../Qt/5.10.1_MinGW_static/mkspecs/features/spec_pre.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/qdevice.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/device_config.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/common/sanitize.conf \
		../../Qt/5.10.1_MinGW_static/mkspecs/common/gcc-base.conf \
		../../Qt/5.10.1_MinGW_static/mkspecs/common/g++-base.conf \
		../../Qt/5.10.1_MinGW_static/mkspecs/common/angle.conf \
		../../Qt/5.10.1_MinGW_static/mkspecs/common/windows-vulkan.conf \
		../../Qt/5.10.1_MinGW_static/mkspecs/qconfig.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axbase.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axbase_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axcontainer.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axserver.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axserver_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_winextras.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_winextras_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_dsengine.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtsysteccanbus.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtvectorcanbus.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwebgl.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwindows.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_xinputgamepad.pri \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/qt_functions.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/qt_config.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/win32-g++/qmake.conf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/toolchain.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/default_pre.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/win32/default_pre.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/resolve_config.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/exclusive_builds_post.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/default_post.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/precompile_header.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/warn_on.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/qt.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/resources.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/moc.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/win32/opengl.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/uic.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/qmake_use.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/file_copies.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/win32/windows.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/testcase_targets.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/exceptions.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/yacc.prf \
		../../Qt/5.10.1_MinGW_static/mkspecs/features/lex.prf \
		Bora.pro \
		../../Qt/5.10.1_MinGW_static/lib/qtmain.prl \
		../../Qt/5.10.1_MinGW_static/plugins/printsupport/windowsprintersupport.prl \
		../../Qt/5.10.1_MinGW_static/plugins/styles/qwindowsvistastyle.prl \
		../../Qt/5.10.1_MinGW_static/plugins/platforms/qwindows.prl \
		../../Qt/5.10.1_MinGW_static/plugins/imageformats/qgif.prl \
		../../Qt/5.10.1_MinGW_static/plugins/imageformats/qicns.prl \
		../../Qt/5.10.1_MinGW_static/plugins/imageformats/qico.prl \
		../../Qt/5.10.1_MinGW_static/plugins/imageformats/qjpeg.prl \
		../../Qt/5.10.1_MinGW_static/plugins/imageformats/qtga.prl \
		../../Qt/5.10.1_MinGW_static/plugins/imageformats/qtiff.prl \
		../../Qt/5.10.1_MinGW_static/plugins/imageformats/qwbmp.prl \
		../../Qt/5.10.1_MinGW_static/plugins/imageformats/qwebp.prl \
		../../Qt/5.10.1_MinGW_static/plugins/bearer/qgenericbearer.prl \
		../../Qt/5.10.1_MinGW_static/lib/Qt5PrintSupport.prl \
		../../Qt/5.10.1_MinGW_static/lib/Qt5Widgets.prl \
		../../Qt/5.10.1_MinGW_static/lib/Qt5Gui.prl \
		../../Qt/5.10.1_MinGW_static/lib/Qt5Network.prl \
		../../Qt/5.10.1_MinGW_static/lib/Qt5Core.prl
	$(QMAKE) -o Makefile Bora.pro CONFIG+=release
../../Qt/5.10.1_MinGW_static/mkspecs/features/spec_pre.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/qdevice.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/features/device_config.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/common/sanitize.conf:
../../Qt/5.10.1_MinGW_static/mkspecs/common/gcc-base.conf:
../../Qt/5.10.1_MinGW_static/mkspecs/common/g++-base.conf:
../../Qt/5.10.1_MinGW_static/mkspecs/common/angle.conf:
../../Qt/5.10.1_MinGW_static/mkspecs/common/windows-vulkan.conf:
../../Qt/5.10.1_MinGW_static/mkspecs/qconfig.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axbase.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axbase_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axcontainer.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axserver.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_axserver_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_charts.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_repparser.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_winextras.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_winextras_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_lib_zlib_private.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_dsengine.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qgif.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qicns.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qico.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qjpeg.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qminimal.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qsqlite.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qsvg.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtga.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtiff.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtsysteccanbus.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qttinycanbus.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtvectorcanbus.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwbmp.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwebgl.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwebp.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwindows.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/modules/qt_plugin_xinputgamepad.pri:
../../Qt/5.10.1_MinGW_static/mkspecs/features/qt_functions.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/qt_config.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/win32-g++/qmake.conf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/spec_post.prf:
../.qmake.stash:
../../Qt/5.10.1_MinGW_static/mkspecs/features/exclusive_builds.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/toolchain.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/default_pre.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/win32/default_pre.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/resolve_config.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/exclusive_builds_post.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/default_post.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/precompile_header.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/warn_on.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/qt.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/resources.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/moc.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/win32/opengl.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/uic.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/qmake_use.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/file_copies.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/win32/windows.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/testcase_targets.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/exceptions.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/yacc.prf:
../../Qt/5.10.1_MinGW_static/mkspecs/features/lex.prf:
Bora.pro:
../../Qt/5.10.1_MinGW_static/lib/qtmain.prl:
../../Qt/5.10.1_MinGW_static/plugins/printsupport/windowsprintersupport.prl:
../../Qt/5.10.1_MinGW_static/plugins/styles/qwindowsvistastyle.prl:
../../Qt/5.10.1_MinGW_static/plugins/platforms/qwindows.prl:
../../Qt/5.10.1_MinGW_static/plugins/imageformats/qgif.prl:
../../Qt/5.10.1_MinGW_static/plugins/imageformats/qicns.prl:
../../Qt/5.10.1_MinGW_static/plugins/imageformats/qico.prl:
../../Qt/5.10.1_MinGW_static/plugins/imageformats/qjpeg.prl:
../../Qt/5.10.1_MinGW_static/plugins/imageformats/qtga.prl:
../../Qt/5.10.1_MinGW_static/plugins/imageformats/qtiff.prl:
../../Qt/5.10.1_MinGW_static/plugins/imageformats/qwbmp.prl:
../../Qt/5.10.1_MinGW_static/plugins/imageformats/qwebp.prl:
../../Qt/5.10.1_MinGW_static/plugins/bearer/qgenericbearer.prl:
../../Qt/5.10.1_MinGW_static/lib/Qt5PrintSupport.prl:
../../Qt/5.10.1_MinGW_static/lib/Qt5Widgets.prl:
../../Qt/5.10.1_MinGW_static/lib/Qt5Gui.prl:
../../Qt/5.10.1_MinGW_static/lib/Qt5Network.prl:
../../Qt/5.10.1_MinGW_static/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Bora.pro CONFIG+=release

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
	-$(DEL_FILE) C:/deps/BeetleCoin-master/src/leveldb/libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) C:/deps/BeetleCoin-master/src/leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) clean
	-$(DEL_FILE) C:/deps/BeetleCoin-master/src/secp256k1/src/libsecp256k1_la-secp256k1.o;
	-$(DEL_FILE) cd
	-$(DEL_FILE) C:/deps/BeetleCoin-master/src/secp256k1;
	-$(DEL_FILE) clean
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:/deps/BeetleCoin-master/bora-qt_plugin_import.cpp

C:/deps/BeetleCoin-master/src/leveldb/libleveldb.a: FORCE

C:/deps/BeetleCoin-master/src/secp256k1/src/libsecp256k1_la-secp256k1.o: FORCE
	cd C:/deps/BeetleCoin-master/src/secp256k1 && ./autogen.sh && ./configure --enable-module-recovery && CC=gcc CXX=g++ $(MAKE) OPT="-fno-keep-inline-dllexport -D_FORTIFY_SOURCE=2 -O2"

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
